export const GOALS = [
  {key: 'poverty', label: 'No Poverty'},
  {key: 'hunger', label: 'Zero Hunger'},
  {key: 'health', label: 'Good Health and Well-being'},
  {key: 'education', label: 'Quality Education'},
  {key: 'genderEquality', label: 'Gender Equality'},
  {key: 'sanitation', label: 'Clean Water and Sanitation'},
  {key: 'energy', label: 'Affordable and Clean Energy'},
  {key: 'economy', label: 'Decent Work and Economic Growth'},
  {key: 'industry, Innovation and Infrastructure', label: 'Industry, Innovation and Infrastructure'},
  {key: 'inequality', label: 'Reduced Inequality'},
  {key: 'sustainability', label: 'Sustainable Cities and Communities'},
  {key: 'consumptionProduction', label: 'Responsible Consumption and Production'},
  {key: 'climateAction', label: 'Climate Action'},
  {key: 'belowWater', label: 'Life Below Water'},
  {key: 'onLand', label: 'Life on Land'},
  {key: 'peace', label: 'Peace and Justice Strong Institutions'},
  {key: 'partnerships', label: 'Partnerships to achieve the Goal'},
]
